package Activities;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class Activity_13 {

    public static void main(String[] args) {
        Scanner myobj = new Scanner(System.in);
        List<Integer> myList = new ArrayList<>();
        Random indexGen = new Random();
        System.out.println("Provide integer value for the ArrayList and type string to exit");

        while(myobj.hasNextInt()){
            myList.add(myobj.nextInt());
        }
        Object[] arr = myList.toArray();
        int n = arr.length;
        int rndnum = indexGen.nextInt(n);
        System.out.println("Indeax value generated by random function is: " + rndnum);
        System.out.println("At Index value "+ rndnum +" we have " + arr[rndnum]);
        myobj.close();
    }
}
